Recover password
donvico/blackhole pull request #32
Opened 2023-10-18 07:49 UTC by donvico

2023-10-18 10:40 UTC, bolowys33 commented on middleware/password.recovery.js
> +const dotenv = require('promise-dotenv').config()
We are to use the normal dotenv

2023-10-18 10:42 UTC, bolowys33 commented on middleware/password.recovery.js
> +  user.passwordResetToken = token;
I don't understand this part, why are you saving the token in the user model?

2023-10-18 10:51 UTC, bolowys33 commented on middleware/password.recovery.js
> +  try{
The trycatch may  not be necessary as the sendMail method takes a callback

`transporter.sendMail(mailOptions, (error, info) => {
    if (error) {
      console.error("Error sending email: " + error);
    } else {
      console.log("Email sent: " + info.response);
    }
  });`

2023-10-20 09:45 UTC, promise-J requested changes

2023-10-20 09:45 UTC, promise-J commented on middleware/password.recovery.js
> +const dotenv = require("promise-dotenv").config()
you can change this to dotenv instead of promise-dotenv. 
We agreed on using the dotenv

2023-10-25 14:46 UTC, merged